# LibreLane configuration file

DESIGN_NAME: heichips25_tiny_wrapper
VERILOG_FILES: [
  "dir::../src/heichips25_tiny_wrapper.sv",
  "dir::../submodules/heichips25-ppwm/src/heichips25_ppwm.sv",
  "dir::../submodules/heichips25-ppwm/src/ppwm_pkg.sv",
  "dir::../submodules/heichips25-ppwm/src/ppwm.sv",
  "dir::../submodules/heichips25-ppwm/src/counter.sv",
  "dir::../submodules/heichips25-ppwm/src/pwm.sv",
  "dir::../submodules/heichips25-ppwm/src/ex.sv",
  "dir::../submodules/heichips25-ppwm/src/mem.sv",
  "dir::../submodules/heichips25_SDR_new/src/heichips25_template.sv",
  "dir::../submodules/heichips25_SDR_new/src/matrix_accumulator.sv",
  "dir::../submodules/heichips25_SDR_new/src/MAC4x4.sv",
  "dir::../submodules/heichips25_SDR_new/src/InputProces.sv",
  "dir::../submodules/heichips25_SDR_new/src/DP_Matrix_G.sv"
]
CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
USE_SLANG: true
